using Microsoft.CodeAnalysis.Text;
using System.Text;

namespace NoahStolk.StrictEnums.SourceGen.Utils;

public static class SourceBuilderUtils
{
	public const string NewLine = "\r\n";

	private const string _fileHeader = """
		// <auto-generated>
		// This code was generated by NoahStolk.StrictEnum.SourceGen.
		// </auto-generated>
		""";

	public static SourceText Build(string sourceCode)
	{
		return SourceText.From($"{_fileHeader}{NewLine}{NewLine}#nullable enable{NewLine}{NewLine}{sourceCode}{NewLine}", Encoding.UTF8);
	}

	public static string IndentCode(this string code, int count)
	{
		string indentation = new('\t', count);
		return code.Replace(NewLine, NewLine + indentation);
	}
}
